{{- if .Values.secret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata: {name: {{ include "sample-api.fullname" . }}}
spec:
  refreshInterval: 1h
  secretStoreRef: {name: {{ .Values.secret.secretStoreName }}, kind: ClusterSecretStore}
  target: {name: {{ include "sample-api.fullname" . }}}
  dataFrom: [{extract: {key: {{ .Values.secret.remoteKey }}}}]
{{- end }}
